namespace SiAB.Core.Entities.Sipffaa;

public class ConsultaMiembro
{
        public int CodMiembro { get; set; }
        public string NombreCompleto { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Cedula { get; set; }
        public string NombreApellidoCompleto { get; set; }
        public string sexo { get; set; }
        public int CodInstitucion { get; set; }
        public string SiglasInstitucion { get; set; }
        public string Institucion { get; set; }
        public int CodNacionalidad { get; set; }
        public string Nacionalidad { get; set; }
        public int CodProfesion { get; set; }
        public string Profesion { get; set; }
        public string ProfesionReal { get; set; }
        public int CodNivelAcademico { get; set; }
        public string NivelAcademico { get; set; }
        public int CodNivelProfesion { get; set; }
        public string NivelProfesion { get; set; }
        public int CodRamaProfesion { get; set; }
        public string RamaProfesion { get; set; }
        public int CodEspecialidad { get; set; }
        public string Especialidad { get; set; }
        public int CodSubEspecialidad { get; set; }
        public string SubEspecialidad { get; set; }
        public int CodEstadoCivil { get; set; }
        public string EstadoCivil { get; set; }
        public int CodRango { get; set; }
        public string Rango { get; set; }
        public string RangoAbreviado { get; set; }
        public string NivelRango { get; set; }
        public int CodDepartamento { get; set; }
        public string Departamento { get; set; }
        public string CategoriaDepartamento { get; set; }
        public string CategoriaOrganicaDepartamento { get; set; }
        public int CodCargo { get; set; }
        public string Estado { get; set; }
        public int CodCompania { get; set; }
        public string Compania { get; set; }
        public int CodBatallon { get; set; }
        public string Batallon { get; set; }
        public int CodBrigada { get; set; }
        public string Brigada { get; set; }
        public int CodTipoIngreso { get; set; }
        public string TipoIngreso { get; set; }
        public Nullable<int> CodTipLicConducir { get; set; }
        public string LicenciaConducir { get; set; }
        public int CodLugarNacimiento { get; set; }
        public string LugarNacimiento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string OficioQueManeja { get; set; }
        public int EdadIngreso { get; set; }
        public string OcupacionAntesIngreso { get; set; }
        public string MotivoIngreso { get; set; }
        public string Estatura { get; set; }
        public decimal Pesos { get; set; }
        public int CodColorPiel { get; set; }
        public string ColorPiel { get; set; }
        public int CodColorOjos { get; set; }
        public string ColorOjos { get; set; }
        public int CodTipoPelo { get; set; }
        public string TipoPiel { get; set; }
        public int CodTipoSangre { get; set; }
        public string TipoSangre { get; set; }
        public string MarcasSicatrices { get; set; }
        public int CodEstadoMiembro { get; set; }
        public string EstadoMiembro { get; set; }
        public string CategoriaEstatus { get; set; }
        public Nullable<bool> EsReingreso { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> CodUsuario { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> FechaUltimoAscenso { get; set; }
        public bool FueDepuradoMedicamente { get; set; }
        public bool FueDepurado { get; set; }
        public string Cargo { get; set; }
        public string DescripcionCargo { get; set; }
        public bool VaParaDepuracion { get; set; }
        public bool FueDepuradoPsicologicamente { get; set; }
        public string CodAnterior { get; set; }
        public int Expr1 { get; set; }
        public int CodCategoriaDepartamento { get; set; }
        public int CodNivelRango { get; set; }
        public string Documento { get; set; }
        public Nullable<int> CodTipoDocumento { get; set; }
        public string TipoDocumento { get; set; }
        public string DescripcionRango { get; set; }
        public string NoCarnet { get; set; }
        public string ArticuloPorGenero { get; set; }
        public Nullable<decimal> SueldoRango { get; set; }
        public Nullable<decimal> SueldoPorRiesgo { get; set; }
        public int CodCategoriaEstatus { get; set; }
        public int NoOrdenRango { get; set; }
        public Nullable<int> CodNivel { get; set; }
        public bool Comando { get; set; }
        public Nullable<bool> GraduadoAcademia { get; set; }
        public Nullable<int> CodPromocionAcademia { get; set; }
        public Nullable<int> NoEscalafonGeneral { get; set; }
        public Nullable<int> NoEscalafonPorNivelProfesional { get; set; }
        public Nullable<int> NoEscalafonPorProfesion { get; set; }
        public Nullable<int> NoEscalafonPorProfesionRango { get; set; }
        public bool EsMilitar { get; set; }
        public string AnosEnRangoActual1 { get; set; }
        public string AnosEnLaInstitucion1 { get; set; }
        public string Edad1 { get; set; }
        public Nullable<int> AnosEnRangoActual { get; set; }
        public Nullable<int> AnosEnLaInstitucion { get; set; }
        public Nullable<int> Edad { get; set; }
        public decimal Sueldo { get; set; }
        public decimal SueldoCargo { get; set; }
        public decimal SueldoRiesgo { get; set; }
        public decimal CompensacionEspecial { get; set; }
        public decimal Prima { get; set; }
        public string Slogan { get; set; }
        public Nullable<int> CodRangoSiguiente { get; set; }
        public int NoOrdenProfesion { get; set; }
        public string TipoPelo { get; set; }
        public string r { get; set; }
        public string RangoIngreso { get; set; }
        public Nullable<System.DateTime> FechaDeIngreso { get; set; }
        public Nullable<System.DateTime> FechaUltimoMovimiento { get; set; }
        public string AnosEnLaFuncionActual { get; set; }
        public string Notificacion { get; set; }
        public Nullable<int> Escalafon { get; set; }
        public Nullable<System.DateTime> FechaCalculadaTiempoServicio { get; set; }
        public Nullable<System.DateTime> FechaCalculadaTiempoRango { get; set; }
        public Nullable<System.DateTime> FechaCalculadaTiempoInstitucion { get; set; }
        public Nullable<System.DateTime> FechaReingreso { get; set; }
        public Nullable<int> CodOrden { get; set; }
        public string OrganoEjecutor { get; set; }
        public Nullable<int> CodOrganoEjecutor { get; set; }
}