
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiAB.Core.Entities.Sipffaa;

public class Miembro
{
        public int CodMiembro { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Cedula { get; set; }
        public string Sexo { get; set; }
        public int CodInstitucion { get; set; }
        public int CodNacionalidad { get; set; }
        public int CodProfesion { get; set; }
        public int CodEspecialidad { get; set; }
        public int CodSubEspecialidad { get; set; }
        public int CodEstadoCivil { get; set; }
        public int CodRango { get; set; }
        public int CodDepartamento { get; set; }
        public int CodCargo { get; set; }
        public int CodCompania { get; set; }
        public int CodTipoIngreso { get; set; }
        public Nullable<int> CodTipLicConducir { get; set; }
        public int CodLugarNacimiento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string OficioQueManeja { get; set; }
        public int EdadIngreso { get; set; }
        public string OcupacionAntesIngreso { get; set; }
        public string MotivoIngreso { get; set; }
        public string Estatura { get; set; }
        public decimal Pesos { get; set; }
        public int CodColorPiel { get; set; }
        public int CodColorOjos { get; set; }
        public int CodTipoPelo { get; set; }
        public int CodTipoSangre { get; set; }
        public string MarcasSicatrices { get; set; }
        public string Descripcion { get; set; }
        public int CodEstadoMiembro { get; set; }
        public Nullable<bool> EsReingreso { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> CodUsuario { get; set; }
        public bool Status { get; set; }
        public Nullable<int> CodComentario { get; set; }
        public Nullable<System.DateTime> FechaUltimoAscenso { get; set; }
        public bool FueDepuradoMedicamente { get; set; }
        public bool FueDepurado { get; set; }
        public bool VaParaDepuracion { get; set; }
        public bool FueDepuradoPsicologicamente { get; set; }
        public string CodAnterior { get; set; }
        public string NombreCompleto { get; set; }
        public string CodigoDeRegistro { get; set; }
        public string FOTO_FileExtension { get; set; }
        public string FOTO_ContentType { get; set; }
        public Nullable<long> FOTO_fileSize { get; set; }
        public string FOTO_THUMBNAIL_FileExtension { get; set; }
        public string FOTO_THUMBNAIL__ContentType { get; set; }
        public Nullable<long> FOTO_THUMBNAIL__fileSize { get; set; }
        public byte[] FOTO_THUMBNAIL__Content { get; set; }
        public bool EsContratado { get; set; }
        public Nullable<System.DateTime> FechaInicioContrato { get; set; }
        public Nullable<System.DateTime> FechaFinalContrato { get; set; }
        public Nullable<System.DateTime> FechaUltimaRenovacionContrato { get; set; }
        public string RecomendadoPor { get; set; }
        public string RecomendadoPorCedula { get; set; }
        public string RecomendacionPorComentario { get; set; }
        public decimal Sueldo { get; set; }
        public decimal SueldoCargo { get; set; }
        public decimal SueldoRiesgo { get; set; }
        public decimal CompensacionEspecial { get; set; }
        public decimal Prima { get; set; }
        public Nullable<decimal> SizeZapatoBota { get; set; }
        public Nullable<decimal> SizePantalon { get; set; }
        public int CodSizeCamisaChaqueta { get; set; }
        public Nullable<decimal> SizeQuepiGorra { get; set; }
        public int CodTipoDocumentoIdentificacion { get; set; }
        public string Documento { get; set; }
        public Nullable<int> CodTipoDocumento { get; set; }
        public Nullable<bool> FueBautizado { get; set; }
        public Nullable<bool> RealizoPrimeraComunion { get; set; }
        public Nullable<bool> RealizoConfirmacion { get; set; }
        public string NoCarnet { get; set; }
        public string Tarjeta { get; set; }
        public string NoCuenta { get; set; }
        public string FullTextLookup { get; set; }
        public Nullable<int> NoEscalafonGeneral { get; set; }
        public Nullable<int> NoEscalafonPorNivelProfesional { get; set; }
        public Nullable<int> NoEscalafonPorProfesion { get; set; }
        public Nullable<int> NoEscalafonPorProfesionRango { get; set; }
        public bool Comando { get; set; }
        public Nullable<bool> GraduadoAcademia { get; set; }
        public Nullable<int> CodPromocionAcademia { get; set; }
        public Nullable<int> CodDepartamentoPagoMIDE { get; set; }
        public Nullable<int> NoEscalafonPorProfesionRangoPorInstitucion { get; set; }
        public byte[] foto { get; set; }
        public string Notificacion { get; set; }
        public Nullable<int> Escalafon { get; set; }
        public Nullable<System.DateTime> FechaCalculadaTiempoServicio { get; set; }
        public Nullable<System.DateTime> FechaCalculadaTiempoRango { get; set; }
        public Nullable<System.DateTime> FechaCalculadaTiempoInstitucion { get; set; }
        public Nullable<System.DateTime> FechaReingreso { get; set; }
        public Nullable<int> CodOrganoEjecutor { get; set; }
}