using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SiAB.Core.Enums
{
	public enum UsuarioRolesEnum
	{
		ADMINISTRADOR_GENERAL = 1,
		MODULO_EXISTENCIAS = 2,
		MODULO_TRANSACCIONES = 3,
		TRANSACCIONES_CREAR_CARGO_DESCARGO = 4,
		TRANSACCIONES_VISUALIZAR_DETALLES = 5,
		TRANSACCIONES_VISUALIZAR_DOCUMENTOS = 6,
		TRANSACCIONES_GENERAR_FORMULARIO_53 = 7,
		TRANSACCIONES_ADJUNTAR_FORMULARIO_53 = 8,
		TRANSACCIONES_CARGAR_INVENTARIO_EXCEL = 9,
		MODULO_MANTENIMIENTO = 10,
		MANTENIMIENTO_INSTITUCIONES = 11,
		MANTENIMIENTO_PROPIEDADES = 12,
		MANTENIMIENTO_ARTICULOS = 13,
		MANTENIMIENTO_TIPOS = 14,
		MANTENIMIENTO_SUBTIPOS = 15,
		MANTENIMIENTO_TIPOS_DOCUMENTOS = 16,
		MANTENIMIENTO_CALIBRES = 17,
		MANTENIMIENTO_MARCAS = 18,
		MANTENIMIENTO_MODELOS = 19,
		MANTENIMIENTO_CATEGORIAS = 20,
		MODULO_EMPRESAS = 21,
		EMPRESAS_CREAR = 22,
		EMPRESAS_EDITAR = 23,
		EMPRESAS_ELIMINAR = 24,
		EMPRESAS_VISUALIZAR_ORDENES = 25,
		EMPRESAS_CREAR_ORDEN = 26,
		EMPRESAS_EDITAR_ORDEN = 27,
		EMPRESAS_ELIMINAR_ORDEN = 28,
		EMPRESAS_VISUALIZAR_DETALLES_ORDEN = 29,
		EMPRESAS_VISUALIZAR_DOCUMENTOS_ORDEN = 30,
		MODULO_USUARIOS = 31
	}
}


